[[redirects]]
  from = 'https://localhost:5000'
  to = 'https://mern-backend-gk2t.onrender.com'
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"